{% set version = "5.14.0" %}

package:
  name: gatsby-cli
  version: {{ version }}

source:
  url: https://registry.npmjs.org/gatsby-cli/-/gatsby-cli-{{ version }}.tgz
  sha256: 7e2769d985ed6e008fb2c75a57b55c543c44237bc10b289632ddf504d39c35db

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - findutils
    - jq
    - make
    - nodejs
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
  run:
    - nodejs
    - xsel  # [linux]

test:
  commands:
    - gatsby --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The best React-based framework with performance, scalability and security built in.
  home: https://github.com/gatsbyjs/gatsby-cli
  dev_url: https://github.com/gatsbyjs/gatsby-cli

extra:
  recipe-maintainers:
    - danielnachun
